#!/usr/bin/env bash
set -euo pipefail

ARCH="${1:-}"

if [[ -z "$ARCH" ]]; then
  if command -v nvidia-smi >/dev/null 2>&1; then
    CAP="$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader | head -n1 | tr -d ' .')"
    if [[ -n "$CAP" ]]; then
      ARCH="sm_${CAP}"
    fi
  fi
fi

if [[ -z "$ARCH" ]]; then
  ARCH="sm_86"
fi

cat > config.ninja <<EOF
# Auto-generated by scripts/configure_ninja.sh
nvcc = nvcc
cuda_arch = $ARCH
arch_flags = -arch=\$cuda_arch
opt_flags = -O3
cuda_flags = -std=c++20 \$opt_flags \$arch_flags --expt-relaxed-constexpr
EOF

echo "Wrote config.ninja with cuda_arch=$ARCH"
echo "Now run: ninja"
