from __future__ import annotations

import csv
import copy
from pathlib import Path
from typing import Iterable, List, Tuple

from .model import Rule, Scope, Settings
from .evaluator import Evaluator


def load_candidate_chunks(path: str | Path, limit: int | None = None) -> list[dict]:
    rows = []
    with Path(path).open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            if not row.get("chunk"):
                continue
            rows.append(row)
            if limit is not None and len(rows) >= limit:
                break
    return rows


def score_rules(rules: list[Rule], settings: Settings, lexicon: dict[str, int], article_text: str) -> dict:
    ev = Evaluator(rules, settings, lexicon)
    _, summary = ev.evaluate_text(article_text)
    return summary


def greedy_add_rules(
    base_rules: list[Rule],
    settings: Settings,
    lexicon: dict[str, int],
    article_text: str,
    candidates: list[dict],
    alphabet: str = "abcdefghijklmnopqrstuvwxyz",
    iterations: int = 10,
    collision_weight: float = 0.0,
) -> tuple[list[Rule], list[dict]]:
    """Prototype greedy search.

    For each step, try adding one candidate chunk mapped to each key.
    Choose the one that minimizes total_cost plus optional collision penalty.

    This is intentionally simple and CPU-bound. It is meant to validate the
    project architecture before C++/CUDA acceleration.
    """
    rules = list(base_rules)
    log = []

    def objective(summary: dict) -> float:
        return float(summary["total_cost"]) + collision_weight * float(summary.get("candidate_code_count", 0))

    seen = {(r.chunk, r.code, r.scope.value) for r in rules}

    current_summary = score_rules(rules, settings, lexicon, article_text)
    current_obj = objective(current_summary)

    for step in range(iterations):
        best = None
        best_summary = None
        best_obj = current_obj

        for c in candidates:
            chunk = str(c["chunk"]).lower()
            if not chunk.isalpha() or len(chunk) < 2:
                continue
            scope = Scope(str(c.get("suggested_scope", "any")).lower())
            for key in alphabet:
                sig = (chunk, key, scope.value)
                if sig in seen:
                    continue
                trial_rule = Rule(
                    rule_id=f"auto_{chunk}_{key}_{scope.value}",
                    chunk=chunk,
                    code=key,
                    scope=scope,
                    cls="auto",
                    enabled=True,
                    group=f"auto_{chunk}",
                    note="generated by greedy_add_rules",
                )
                trial_rules = rules + [trial_rule]
                summary = score_rules(trial_rules, settings, lexicon, article_text)
                obj = objective(summary)
                if obj < best_obj:
                    best_obj = obj
                    best = trial_rule
                    best_summary = summary

        if best is None:
            log.append({"step": step, "action": "stop", "reason": "no_improvement", "objective": current_obj})
            break

        rules.append(best)
        seen.add((best.chunk, best.code, best.scope.value))
        current_obj = best_obj
        current_summary = best_summary or current_summary
        log.append({
            "step": step,
            "action": "add",
            "chunk": best.chunk,
            "code": best.code,
            "scope": best.scope.value,
            "objective": current_obj,
            "total_cost": current_summary["total_cost"],
            "reduction_ratio": current_summary["reduction_ratio"],
        })

    return rules, log
